"""baseline_schema_v1

Revision ID: 99c8ce339dd4
Revises: 
Create Date: 2026-09-12 16:30:35.998104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c8ce339dd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_active_session_candidate_exam', 'candidate_sessions', ['candidate_id', 'exam_id'], unique=True, postgresql_where="status = 'ACTIVE'", sqlite_where="status = 'ACTIVE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_active_session_candidate_exam', table_name='candidate_sessions', postgresql_where="status = 'ACTIVE'", sqlite_where="status = 'ACTIVE'")
    # ### end Alembic commands ###
