"""baseline_schema_v1

Revision ID: 99c8ce339dd4
Revises: 
Create Date: 2026-09-12 22:28:50.969448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c8ce339dd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', 'BLOCKED', 'WARNING', name='auditresult'), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('prev_hash', sa.String(length=128), nullable=False),
    sa.Column('event_hash', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('org_type', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('exam_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_event_actor', 'security_events', ['actor_id'], unique=False)
    op.create_index('ix_security_event_created', 'security_events', ['created_at'], unique=False)
    op.create_index('ix_security_event_type_severity', 'security_events', ['event_type', 'severity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'EXAM_AUTHORITY', 'QUESTION_SETTER', 'REVIEWER', 'MODERATOR', 'SECURITY_OFFICER', 'RELEASE_AUTHORITY', 'CENTRE_ADMIN', 'INVIGILATOR', 'CANDIDATE', 'AUDITOR', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_org_role', 'users', ['org_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email_hash', sa.String(length=128), nullable=False),
    sa.Column('phone_hash', sa.String(length=128), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index('ix_candidate_org', 'candidates', ['org_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exam_type', sa.String(length=100), nullable=False),
    sa.Column('security_mode', sa.Enum('STANDARD', 'HIGH', 'CRITICAL', name='securitymode'), nullable=False),
    sa.Column('scheduled_start_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'BLUEPRINT_CREATED', 'FORMS_GENERATED', 'THRESHOLD_PENDING', 'THRESHOLD_APPROVED', 'RELEASED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'FROZEN', name='examstatus'), nullable=False),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('min_centre_readiness_pct', sa.Float(), nullable=False),
    sa.Column('release_frozen', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exams_org_status', 'exams', ['org_id', 'status'], unique=False)
    op.create_index('ix_exams_scheduled', 'exams', ['scheduled_start_utc'], unique=False)
    op.create_table('centres',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('centre_code', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'ACTIVE', 'ISOLATED', 'OFFLINE', name='centrestatus'), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centre_code')
    )
    op.create_index('ix_centre_exam_status', 'centres', ['exam_id', 'status'], unique=False)
    op.create_table('exam_blueprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('integrity_hash', sa.String(length=128), nullable=False),
    sa.Column('digital_signature', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('exam_forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('form_label', sa.String(length=10), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('option_orders', sa.JSON(), nullable=False),
    sa.Column('integrity_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'BACKUP', name='formstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'form_label', name='uq_exam_form_label')
    )
    op.create_index('ix_form_exam_status', 'exam_forms', ['exam_id', 'status'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', name='incidentstatus'), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_resource', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('actions_taken', sa.JSON(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_severity_status', 'incidents', ['severity', 'status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('bloom_level', sa.String(length=50), nullable=True),
    sa.Column('question_format', sa.String(length=50), nullable=False),
    sa.Column('marks_positive', sa.Float(), nullable=False),
    sa.Column('marks_negative', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'ENCRYPTED', 'READY', 'ASSIGNED', 'RELEASED', 'ARCHIVED', 'QUARANTINED', name='questionstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('object_store_key', sa.String(length=500), nullable=True),
    sa.Column('key_reference', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('digital_signature', sa.Text(), nullable=True),
    sa.Column('encrypted_content', sa.Text(), nullable=True),
    sa.Column('encrypted_answer', sa.Text(), nullable=True),
    sa.Column('plaintext_content', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_author', 'questions', ['author_id'], unique=False)
    op.create_index('ix_questions_exam_status', 'questions', ['exam_id', 'status'], unique=False)
    op.create_index('ix_questions_subject_difficulty', 'questions', ['subject', 'difficulty'], unique=False)
    op.create_table('release_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('authority_id', sa.String(length=36), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('approval_signature', sa.Text(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'authority_id', name='uq_exam_authority_approval')
    )
    op.create_index('ix_release_approval_exam', 'release_approvals', ['exam_id'], unique=False)
    op.create_table('answer_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.Column('marks_positive', sa.Float(), nullable=False),
    sa.Column('marks_negative', sa.Float(), nullable=False),
    sa.Column('explanation_encrypted', sa.Text(), nullable=True),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index('ix_answer_key_question', 'answer_keys', ['question_id'], unique=False)
    op.create_table('candidate_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('centre_id', sa.String(length=36), nullable=True),
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('session_key_encrypted', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUBMITTED', 'EXPIRED', 'FLAGGED', 'REVOKED', name='sessionstatus'), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=200), nullable=True),
    sa.Column('tab_switch_count', sa.Integer(), nullable=False),
    sa.Column('security_violations', sa.Integer(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['exam_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_sessions_session_token_hash'), 'candidate_sessions', ['session_token_hash'], unique=True)
    op.create_index('ix_session_candidate_exam', 'candidate_sessions', ['candidate_id', 'exam_id'], unique=False)
    op.create_index('ix_session_status', 'candidate_sessions', ['status'], unique=False)
    op.create_index('uix_active_session_candidate_exam', 'candidate_sessions', ['candidate_id', 'exam_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_table('question_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=True),
    sa.Column('is_marked_review', sa.Boolean(), nullable=False),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['candidate_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_session_question_response')
    )
    op.create_index('ix_response_session', 'responses', ['session_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('incorrect', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('result_signature', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['candidate_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_result_candidate_exam', 'results', ['candidate_id', 'exam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_result_candidate_exam', table_name='results')
    op.drop_table('results')
    op.drop_index('ix_response_session', table_name='responses')
    op.drop_table('responses')
    op.drop_table('question_reviews')
    op.drop_index('uix_active_session_candidate_exam', table_name='candidate_sessions', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_session_status', table_name='candidate_sessions')
    op.drop_index('ix_session_candidate_exam', table_name='candidate_sessions')
    op.drop_index(op.f('ix_candidate_sessions_session_token_hash'), table_name='candidate_sessions')
    op.drop_table('candidate_sessions')
    op.drop_index('ix_answer_key_question', table_name='answer_keys')
    op.drop_table('answer_keys')
    op.drop_index('ix_release_approval_exam', table_name='release_approvals')
    op.drop_table('release_approvals')
    op.drop_index('ix_questions_subject_difficulty', table_name='questions')
    op.drop_index('ix_questions_exam_status', table_name='questions')
    op.drop_index('ix_questions_author', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_incident_severity_status', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_form_exam_status', table_name='exam_forms')
    op.drop_table('exam_forms')
    op.drop_table('exam_blueprints')
    op.drop_index('ix_centre_exam_status', table_name='centres')
    op.drop_table('centres')
    op.drop_index('ix_exams_scheduled', table_name='exams')
    op.drop_index('ix_exams_org_status', table_name='exams')
    op.drop_table('exams')
    op.drop_index('ix_candidate_org', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_org_role', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_security_event_type_severity', table_name='security_events')
    op.drop_index('ix_security_event_created', table_name='security_events')
    op.drop_index('ix_security_event_actor', table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('organizations')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index('ix_audit_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')

    # Drop custom PostgreSQL ENUM types so re-upgrade succeeds cleanly
    sa.Enum(name='sessionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='questionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incidentstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incidentseverity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='formstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='centrestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='examstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='securitymode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='userroleenum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='auditresult').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

