"""add question assignments

Revision ID: a2f3b4c5d6e7
Revises: 99c8ce339dd4
Create Date: 2026-09-13 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f3b4c5d6e7'
down_revision: Union[str, None] = '99c8ce339dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_assignments',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('question_id', sa.String(length=36), nullable=False),
        sa.Column('reviewer_id', sa.String(length=36), nullable=False),
        sa.Column('exam_id', sa.String(length=36), nullable=False),
        sa.Column('assigned_by', sa.String(length=36), nullable=False),
        sa.Column('purpose', sa.Enum('TECHNICAL_REVIEW', 'SYLLABUS_REVIEW', 'LANGUAGE_REVIEW', 'DISTRACTOR_REVIEW', 'KEY_VERIFICATION', name='reviewpurpose'), nullable=False),
        sa.Column('status', sa.Enum('ACTIVE', 'IN_REVIEW', 'COMPLETED', 'REVOKED', name='questionassignmentstatus'), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revocation_reason', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qassign_exam_status', 'question_assignments', ['exam_id', 'status'], unique=False)
    op.create_index('ix_qassign_question_status', 'question_assignments', ['question_id', 'status'], unique=False)
    op.create_index('ix_qassign_reviewer_status', 'question_assignments', ['reviewer_id', 'status'], unique=False)
    op.create_index(
        'uix_active_question_reviewer_assignment',
        'question_assignments',
        ['question_id', 'reviewer_id'],
        unique=True,
        postgresql_where=sa.text("status IN ('ACTIVE', 'IN_REVIEW')"),
        sqlite_where=sa.text("status IN ('ACTIVE', 'IN_REVIEW')")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uix_active_question_reviewer_assignment',
        table_name='question_assignments',
        postgresql_where=sa.text("status IN ('ACTIVE', 'IN_REVIEW')"),
        sqlite_where=sa.text("status IN ('ACTIVE', 'IN_REVIEW')")
    )
    op.drop_index('ix_qassign_reviewer_status', table_name='question_assignments')
    op.drop_index('ix_qassign_question_status', table_name='question_assignments')
    op.drop_index('ix_qassign_exam_status', table_name='question_assignments')
    op.drop_table('question_assignments')

    sa.Enum(name='reviewpurpose').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='questionassignmentstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
